name: Production
on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ideaux-pro
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: "pro"
          
      - name: Install Packages & Setup
        run: |
         sudo service nginx restart
